sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t sandipan814/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true sandipan814/react-test npm test -- --coverage
after_success:
    - docker build -t sandipan814/multi-client ./client
    - docker build -t sandipan814/multi-server ./server
    - docker build -t sandipan814/multi-worker ./worker
    - docker build -t sandipan814/multi-nginx ./nginx
    #Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images to docker hu
    - docker push sandipan814/multi-client
    - docker push sandipan814/multi-server
    - docker push sandipan814/multi-worker
    - docker push sandipan814/multi-nginx

